version: "3"

  # docker run --privileged --device /dev/fuse -v /mnt:/mnt:shared -it jammy-test /bin/bash

services: 
  ceph-fuse: 
    build: .
    privileged: true
    cap_add:
      - ALL
    stdin_open: true
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes: 
      - /mnt:/mnt:shared
